apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mini-projet
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-replicaset
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: eazytraining
            - name: MYSQL_USER
              value: eazy
            - name: MYSQL_PASSWORD
              value: eazy
          ports:
            - containerPort: 3306
          imagePullPolicy: IfNotPresent
      