apiVersion: v1
kind: Service
metadata:
  name: nodeport-wordpress
  namespace: mini-projet
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
