apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: mysql-volume
spec:
  containers:
    - name: mysql-volume
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data-volume
  volumes:
    - name: mysql-data-volume
      hostPath:
        path: /data-volume
  