apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: mmumshad/simple-webapp-color
      env:
        - name: APP_COLOR
          value: red
      ports:
        - containerPort: 8080