apiVersion: v1
kind: Service
metadata:
  name: nodeport-web
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
